<a href="https://colab.research.google.com/github/yasreddi/Machine-Learning-Models/blob/main/linear-regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
import pandas as pd
import numpy as nm

In [41]:
from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/bpp.csv') #reading the dataset into dataframe

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [42]:
X = df.drop(["SalePrice","Hydraulics_Flow","Coupler_System","Grouser_Tracks","ModelID","Forks","Stick","Enclosure","Turbocharged","Pad_Type","MachineID","Drive_System","SalesID","Coupler","saleMonth","auctioneerID"],axis=1) #Input features (remove features with null values,unwanted metrics and un processed data)
y= df[["SalePrice"]] #Output

In [43]:
df=df.dropna(axis=0)

In [44]:
from sklearn.model_selection import train_test_split #splitting the data test size 25%
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [45]:
from sklearn.preprocessing import StandardScaler # scaling the data or normalizing the data z = (x - u) / s (u=mean and s=standard deviation)
ss = StandardScaler()
X_train_scaled = ss.fit_transform(X_train) # scaling both train data and test data
X_test_scaled = ss.transform(X_test)

In [46]:
X_train_scaled

array([[-0.10638847,  0.3158155 , -0.21377279, ..., -0.01750803,
        -1.41624323, -0.21377279],
       [-0.10638847,  0.3301504 , -1.07030327, ...,  0.1707414 ,
        -1.17837765, -1.07030327],
       [-0.10638847,  0.26564336,  0.21449245, ..., -2.27650123,
         0.36774865,  0.21449245],
       ...,
       [-0.10638847,  0.29431316, -0.00439868, ..., -0.01750803,
         1.20027819, -0.00439868],
       [-0.10638847,  0.32656668, -0.13763675, ...,  0.1707414 ,
        -0.46478089, -0.13763675],
       [-0.10638847,  0.32656668,  1.63252624, ..., -0.20575747,
        -0.10798252,  1.63252624]])

In [47]:
from sklearn.linear_model import LinearRegression #training the model or finding the weights

linear_model = LinearRegression().fit(X_train_scaled,y_train)

In [48]:
linear_model.intercept_  # the constant value

array([31008.74960444])

In [49]:
linear_model.coef_ # the weights

array([[  -507.87726198,   3246.38141218,   -283.67828531,
          1654.18885138,  -4857.38016477,   4352.3162694 ,
          3703.09655748,   1992.91273176,   3743.32815578,
          2753.98074104,     75.11064991,   -362.55905324,
          6037.63953049,   6037.63953049,  11130.4925015 ,
          3922.27377603,   2281.99888762,   1088.89015051,
        -12378.31334699,   7846.69158387,    813.01358403,
          5732.59969496,   2051.60300364,   2748.41150961,
          1117.02233228,  -1227.38906063,  13280.88541286,
          -201.9362268 ,  -8874.88206155,  -4952.90396923,
          4287.14136826,    357.42037708,  10007.6468487 ,
          5180.04806121, -18647.63516525,  -4136.35356594,
         -4855.22267088,   -621.51115238,    -98.98040807,
          -283.67828531]])

In [50]:
y_test #actual values

SalePrice
4941         8500
51775       52500
115253      30000
299321      19000
173570      48000
...           ...
150314      12000
208724      38000
84364       76000
217051      38000
173099      22000

[75000 rows x 1 columns]

In [51]:
y_pred = linear_model.predict(X_test_scaled) # prediction

In [52]:
y_pred # predicted values

array([[42518.4024017 ],
       [40448.91903098],
       [25961.20405285],
       ...,
       [61650.09626601],
       [45821.4626941 ],
       [22335.27960266]])

In [53]:
result = pd.DataFrame()
result["Predictions_LR"] = nm.reshape(y_pred,75000)
result["Actual"] = y_test.values

In [54]:
result # result data frame

Predictions_LR  Actual
0        42518.402402    8500
1        40448.919031   52500
2        25961.204053   30000
3        23138.425800   19000
4        41421.438227   48000
...               ...     ...
74995    15813.202997   12000
74996    39367.640477   38000
74997    61650.096266   76000
74998    45821.462694   38000
74999    22335.279603   22000

[75000 rows x 2 columns]

In [55]:
from sklearn.metrics import mean_absolute_error #mean of (|ypred - yactual|)
mean_absolute_error(result["Actual"],result["Predictions_LR"])

12752.257723093138

In [56]:
from sklearn.metrics import mean_absolute_percentage_error #mean of (yactual-ypred/yactual)
mean_absolute_percentage_error(result["Actual"],result["Predictions_LR"])


0.545646993796614

In [57]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.3945167093765194

In [58]:
from sklearn.model_selection import cross_val_score, StratifiedKFold, train_test_split, KFold
# value of K is 10.

kfold = KFold(n_splits=10) #splitting the data

In [62]:
cv_results = cross_val_score(linear_model,X_train_scaled, y_train, cv=kfold) #finding cross validation accuracies

In [63]:
cv_results.mean() #mean of accuracy of 10 validation sets


0.39642022777314195